module.exports = {
  'lato-italic': require('../assets/fonts/Lato/Lato-Italic.ttf'),
  'lato-lightitalic': require('../assets/fonts/Lato/Lato-LightItalic.ttf'),
  'lato-bold': require('../assets/fonts/Lato/Lato-Bold.ttf'),
  'lato-black': require('../assets/fonts/Lato/Lato-Black.ttf'),
  'lato-hairlineitalic': require('../assets/fonts/Lato/Lato-HairlineItalic.ttf'),
  'lato-regular': require('../assets/fonts/Lato/Lato-Regular.ttf'),
  'lato-hairline': require('../assets/fonts/Lato/Lato-Hairline.ttf'),
  'lato-blackitalic': require('../assets/fonts/Lato/Lato-BlackItalic.ttf'),
  'lato-bolditalic': require('../assets/fonts/Lato/Lato-BoldItalic.ttf'),
  'lato-light': require('../assets/fonts/Lato/Lato-Light.ttf'),
  'rubik-mediumitalic': require('../assets/fonts/Rubik/Rubik-MediumItalic.ttf'),
  'rubik-bold': require('../assets/fonts/Rubik/Rubik-Bold.ttf'),
  'rubik-light': require('../assets/fonts/Rubik/Rubik-Light.ttf'),
  'rubik-medium': require('../assets/fonts/Rubik/Rubik-Medium.ttf'),
  'rubik-black': require('../assets/fonts/Rubik/Rubik-Black.ttf'),
  'rubik-italic': require('../assets/fonts/Rubik/Rubik-Italic.ttf'),
  'rubik-lightitalic': require('../assets/fonts/Rubik/Rubik-LightItalic.ttf'),
  'rubik-blackitalic': require('../assets/fonts/Rubik/Rubik-BlackItalic.ttf'),
  'rubik-regular': require('../assets/fonts/Rubik/Rubik-Regular.ttf'),
  'rubik-bolditalic': require('../assets/fonts/Rubik/Rubik-BoldItalic.ttf')
}
